### ISSUE TITLE
Splitting with empty string as separator causes high memory usage

### ISSUE THREAD

**Issue by Esgorhannoth** [h3rald/mn#4]
```
"test" "" split
```
causes high memory usage and heavy swapping, so that PC sometimes even freezes (Windows 10 x64, 8 GB RAM)

My intention was to get separate characters, but according to nim's `split` documentation, with empty separator nim's `split` returns unmodified string. Somehow `split` in mn does neither.

**Comment by h3rald** [comment]
This is really weird, because the split symbol can be used with an empty separator in _min_:

![image](https://github.com/h3rald/mn/assets/1169/93c239ca-78ed-415a-93d4-a951af101218)

...but in _mn_ it hangs. The annoying thing is that the implementation is essentially the same, but perhaps in min if the pcre library is included the behavior changes.

Perhaps the easiest thing would be to handle this as a special case in mn and if the separator is an empty string try to use something else in Nim to split the string, maybe create a sequence via an iterator or something.

**Comment by Esgorhannoth** [comment]
Seems like Nim problem. I have written a simple program to test my suggestion:

```nim
import
     strutils

proc main =
    var i = 0
    echo "hello".split("")    ## compiles, but assertion (sep.len > 0) error at runtime 
    #but
    for e in "hello".split(""):  ## infinite loop
        i.inc
        echo i       ## to confirm that something happens
        echo e

main()
```

Possible solution:
```nim
 def.symbol("split") do (i: In):
    let vals = i.expect("'sym", "'sym")
    let sep = vals[0].getString
    let s = vals[1].getString
    var q = newSeq[MnValue](0)
    if sep.len > 0:
      for e in s.split(sep):
        q.add e.newVal
    else:
      for e in s:
        q.add e.newVal
    i.push q.newVal
```

**Comment by h3rald** [comment]
Fixed on master 😊👍
